### ISSUE TITLE
Allow Selection to contain multiple ranges

### ISSUE THREAD

**Issue by IgnacioHR** [w3c/selection-api#115] opened 2019-12-13 21:31 UTC
The current wording and the implementation on current browsers replaces the existing range on the Selection when addRange(...) is called. As a result, only one Range exists on the Selection.

The example here:
https://developer.mozilla.org/en-US/docs/Web/API/Selection/addRange
suggest that the desired behavior is that the Selection could contain an array of Ranges instead of just one Range

I can think on many other use cases such as using javascript for selecting the content of all columns in a table and add them to the Selection and later perform a copy operation... Today this functionality cannot use current selection-api specification.

I would like to see what other people think about this.

**Comment by rniwa** [comment] 2020-01-22 07:54
This is a duplicate of https://github.com/w3c/selection-api/issues/41.

**Closed as completed by rniwa** 2020-01-22 07:54 UTC
