### ISSUE TITLE
Event handlers missing

### ISSUE THREAD

**Issue by teoli2003** [w3c/selection-api#60] opened 2015-09-27 10:18 UTC
Gecko implemented Document.onselectionchange and GlobalEventHandlers.onselectstart. [1]
Edge does it too (but both on Document [2])
Blink does it too (on both Document too [3])

These event handlers properties should be added to the spec.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=571294
[2] https://dev.modern.ie/platform/documentation/apireference/interfaces/document/
[3] https://chromium.googlesource.com/chromium/blink/+/master/Source/core/dom/Document.idl

**Comment by ehsan** [comment] 2015-09-28 20:29
See #53.

**Comment by rniwa** [comment] 2016-09-20 15:08
This is really a duplicate of the issue #54

Fixed this in https://github.com/w3c/selection-api/commit/64802693414d842d1c0273f9fee019602710fe8c.

**Closed as completed** 2016-09-20 15:09 UTC
Labels: Compatibility
