### ISSUE TITLE
The spec doesn't define event handlers onselectstart and onselectionchange

### ISSUE THREAD

**Issue by smaug----** [w3c/selection-api#55] opened 2015-08-19 12:56 UTC
The spec doesn't define any onfoo event handlers, but IIRC at least some implementations already have them.
Need to spec which interfaces should have onselectstart and onselectionchange.

**Comment by ehsan** [comment] 2015-08-19 16:02
This is a dupe of #54.

**Comment by rniwa** [comment] 2016-01-10 02:37
Right, this is a duplicate of issue #54.

**Closed as completed by rniwa** 2016-01-10 02:37 UTC
