### ISSUE TITLE
Include information about where the selection is ending

### ISSUE THREAD

**Issue by lauradaquila** [w3c/selection-api#93] opened 2017-09-28 12:55 UTC
In the dispatched selectstart events, please include information about where the selection is ending in addition to where the selection is beginning. The selectstart event’s currentTarget attribute only seems to show where the selection begins.

**Comment by rniwa** [comment] 2022-07-13 02:29
Looks like this is a duplicate of the issue #146. Closing for now since the other issue has more discussions. Please let me know if this is about some other issue.

**Closed as completed by rniwa** 2022-07-13 02:29 UTC
